vscode:
    extensions:
        - nrwl.angular-console@9.0.1:M60l7Y3X3KhJmx93JK/8vg==
        - christian-kohler.npm-intellisense@1.3.0:yQtCdwoyo890Bn9NOEuEDA==
        - villematti.js-template-syntax-highlighting@0.0.1:M0FVgKLjQQqUQO8Xl0xN3w==
