# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

pool:
    vmImage: 'ubuntu-latest'

steps:
    - script: export version=$(node -pe "require('./package.json').version") && echo "##vso[task.setvariable variable=PACKAGE_VERSION]$version"
      displayName: 'Define a variable'

    - script: echo "##vso[task.setvariable variable=PACKAGE_VERSION_1]1"
      displayName: 'Define a variable 1'

    - script: echo $PACKAGE_VERSION
      displayName: 'package version'

    - script: echo $PACKAGE_VERSION_1
      displayName: 'package version 1'

    - script: echo "##vso[build.addbuildtag]notrelease"
      displayName: 'package version 1'
